"""Add Review Model

Revision ID: a2d4cc80a1dd
Revises: 29ea06b9001c
Create Date: 2023-09-01 03:13:07.457330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d4cc80a1dd'
down_revision = '29ea06b9001c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
